/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.minepress.gradle

import kotlin.test.Test
import kotlin.test.assertTrue
import org.gradle.testkit.runner.GradleRunner
import org.junit.Rule
import org.junit.rules.TemporaryFolder

class GradleMinepressPluginFunctionalTest {
  @get:Rule val tempFolder = TemporaryFolder()

  private val projectDir
    get() = tempFolder.root
  private val buildFile
    get() = projectDir.resolve("build.gradle")
  private val settingsFile
    get() = projectDir.resolve("settings.gradle")

  @Test
  fun `init task creates minepress folder`() {
    // Setup the test build
    settingsFile.writeText("")
    buildFile.writeText(
        """
            plugins {
                id 'com.minepress'
            }
            """.trimIndent()
    )
    val runner = GradleRunner.create()
    runner.forwardOutput()
    runner.withPluginClasspath()
    runner.withArguments("init")
    runner.withProjectDir(projectDir)
    val result = runner.build()
    val minepressDir = projectDir.resolve("minepress")
    // Verify the result
    assertTrue(
        result.output.contains(
            "Created minepress folder and config.json file in ${minepressDir.absolutePath}"
        )
    )
    assertTrue(minepressDir.exists())
    assertTrue(minepressDir.resolve("config.json").exists())
    assertTrue(minepressDir.resolve("example.test.js").exists())
  }
}
